config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("qnA.urls", namespace="qnA")),
    path("users/", include("users.urls", namespace="users")),
    path("notifications/", include("notifications.urls", namespace="notifications")),
    path("summernote/", include("django_summernote.urls")),
    re_path(r"^comments/", include("django_comments_xtd.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

notifications/urls.py
from django.urls import path
from . import views

app_name = "notifications"
urlpatterns = [
    path("all/", views.NotificationListView.as_view(), name="notifications_all",),
    path(
        "answers/",
        views.NotificationAnswerListView.as_view(),
        name="notifications_ans",
    ),
    path(
        "followed-questions/",
        views.NotificationFollowedQuestionsListView.as_view(),
        name="notifications_followed_questions",
    ),
    path(
        "<int:pk>", views.NotificationDetailView.as_view(), name="notification_detail",
    ),
    path("dismiss/all", views.dismiss_notification, name="dismiss_all_notification",),
    path("dismiss/<int:pk>", views.dismiss_notification, name="dismiss_notification",),
]

qnA/urls.py
from django.urls import path
from . import views

app_name = "qnA"
urlpatterns = [
    path("", views.QnaListView.as_view(), name="home"),
    path(
        "question/<slug:slug>/",
        views.QuestionDetailView.as_view(),
        name="question_detail",
    ),
    path(
        "question/request/<slug:slug>/",
        views.RequestAnswerListView.as_view(),
        name="answer_request",
    ),
    path(
        "question/request/<int:question_pk>/<int:user_pk>",
        views.request_answer,
        name="answer_request_ajax",
    ),
    # passing slugs for SEO purpose
    path(
        "question/<slug:slug>/answer/<slug:user_slug>/<int:question_pk>/<int:user_pk>",
        views.AnswerDetailView.as_view(),
        name="answer_detail",
    ),
    path("ask-question/", views.AskQuestionView.as_view(), name="ask-question"),
    path("answer/<slug:slug>", views.AnswerView.as_view(), name="answer"),
    path("answer/edit/<slug:slug>", views.AnswerUpdateView.as_view(), name="edit"),
    path("answer/delete/<slug:slug>", views.AnswerDeleteView.as_view(), name="delete"),
    path(
        "question/follow/<slug:question_slug>",
        views.follow_question,
        name="follow-question",
    ),
    path("<int:question_id>/vote", views.vote, name="question-vote"),
    path("question/<slug:slug>/<int:question_id>/vote/", views.vote, name="vote"),
    path("search/", views.QnaListView.as_view(), name="search"),
    path(
        "question/<slug:slug>/request/user/",
        views.RequestAnswerListView.as_view(),
        name="search-user",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("profile/<slug:slug>", views.ProfileDetailView.as_view(), name="profile"),
    path(
        "profile/<slug:slug>/questions",
        views.ProfileQuestionListView.as_view(),
        name="profile_questions",
    ),
    path(
        "profile/<slug:slug>/answers",
        views.ProfileAnswerListView.as_view(),
        name="profile_answers",
    ),
    path(
        "profile/<slug:slug>/answers/<str:is_pin>/<int:answer_pk>",
        views.profile_answer_pin,
        name="is_pin_answer",
    ),
    path(
        "profile/<slug:slug>/followers",
        views.ProfileFollowersListView.as_view(),
        name="followers",
    ),
    path(
        "profile/<slug:slug>/following",
        views.ProfileFollowingListView.as_view(),
        name="following",
    ),
    path("edit/", views.ProfileUpdateView.as_view(), name="edit"),
    path("add/workplace/", views.WorkPlaceFormAddView.as_view(), name="workplace_add"),
    path("edit/workplace/", views.WorkPlaceUpdateView.as_view(), name="workplace_edit"),
    path("delete/workplace/", views.delete_workplace, name="workplace_delete"),
    path("add/education/", views.EducationFormAddView.as_view(), name="education_add"),
    path("edit/education/", views.EducationUpdateView.as_view(), name="education_edit"),
    path("delete/education/", views.delete_education, name="education_delete",),
    path(
        "follow_toggle/<slug:slug>",
        views.follow_unfollow_users,
        name="follow_unfollow",
    ),
    path("logout/", views.logout_request, name="logout"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
]

notifications/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from users.models import User
from qnA.models import Question, Answer, FollowQuestion
from users.models import Follow


class Notification(models.Model):
    msg = models.CharField(max_length=255)
    is_seen = models.BooleanField(default=False)
    is_anonymous = models.BooleanField(default=False)
    is_answer = models.BooleanField(default=False)
    is_followed_question = models.BooleanField(default=False)
    is_requested_question = models.BooleanField(default=False)
    """ For sending notification to users who follow a user when the user asks question """
    is_following_user_questions = models.BooleanField(default=False)
    """ For sending notification to users who follow a user when the user answers question """
    is_following_user_answers = models.BooleanField(default=False)
    from_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notification_from_people",
    )
    to_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notification_to_people"
    )
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="notif_question", null=True,
    )
    created_date = models.DateTimeField(auto_now=True)
    # question_slug = models.SlugField()


@receiver(post_save, sender=Follow)
@receiver(post_save, sender=Answer)
def notification(sender, **kwargs):
    if kwargs["created"]:
        """
        When a user upvotes/downvotes an answer, the answer model is modified as answer's vote_score is updated. This if condition ensures that notifications are only sent when a new answer is created and not everytime when someone upvotes/downvotes the ans
        """
        try:
            from_user = kwargs.get("instance").user
            to_user = kwargs.get("instance").question.user
            question = kwargs.get("instance").question
            is_anonymous = kwargs.get("instance").is_anonymous
            if is_anonymous:
                msg = f"An Anonymous user answered your question: {question}"
            else:
                msg = f"{from_user.first_name} {from_user.last_name} answered your question: {question}"
            if from_user != to_user:
                """Not sending notification in scenarios such as user answering his/her own question"""
                Notification.objects.create(
                    from_user=from_user,
                    to_user=to_user,
                    msg=msg,
                    question=question,
                    is_anonymous=is_anonymous,
                    is_answer=True,
                )
            question_followers = FollowQuestion.objects.filter(question=question)
            if is_anonymous:
                # message to the followers of a question
                msg = f"An Anonymous user answered a question you were following: {question}"
            else:
                msg = f"{from_user.first_name} {from_user.last_name} answered a question you were following: {question}"
            for follower in question_followers:
                if from_user != follower.user:
                    """
                    This ensures that if a user follows a question and then answers that question then he/she
                    wouldn't get notification
                    """
                    Notification.objects.create(
                        from_user=from_user,
                        to_user=follower.user,
                        msg=msg,
                        question=question,
                        is_followed_question=True,
                    )
        except:
            from_user = kwargs.get("instance").from_user
            to_user = kwargs.get("instance").to_user
            msg = f"{from_user.first_name} {from_user.last_name} started following you"
            Notification.objects.create(
                from_user=from_user, to_user=to_user, msg=msg,
            )

notifications/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Notification


class NotificationListView(LoginRequiredMixin, ListView):
    model = Notification
    login_url = "/users/login/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        notifications = Notification.objects.filter(
            to_user=self.request.user.pk
        ).order_by("-created_date")
        context["notifications"] = notifications
        return context


class NotificationDetailView(LoginRequiredMixin, DetailView):
    model = Notification
    login_url = "/users/login/"
    queryset = Notification.objects.all()

    def get_context_data(self, **kwargs):
        context = super(NotificationDetailView, self).get_context_data(**kwargs)
        obj = self.get_object()
        obj.is_seen = True
        obj.save()
        from_user = obj.from_user
        to_user = obj.to_user
        question = obj.question
        try:
            ans = question.answer_set.filter(user=from_user.pk)[0]
            context["ans"] = ans
        except:
            pass
        is_requested_question = Notification.objects.filter(
            from_user=from_user,
            to_user=to_user,
            question=question,
            is_requested_question=True,
        )
        is_following_user_questions = Notification.objects.filter(
            from_user=from_user,
            to_user=to_user,
            question=question,
            is_following_user_questions=True,
        )
        is_following_user_answers = Notification.objects.filter(
            from_user=from_user,
            to_user=to_user,
            question=question,
            is_following_user_answers=True,
        )
        context["is_requested_question"] = is_requested_question
        context["is_following_user_answers"] = is_following_user_answers
        context["is_following_user_questions"] = is_following_user_questions
        context["from_user"] = from_user
        context["question"] = question
        return context


class NotificationAnswerListView(LoginRequiredMixin, ListView):
    model = Notification
    login_url = "/users/login/"
    template_name = "notifications/notification_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        notifications = Notification.objects.filter(
            to_user=self.request.user.pk, is_answer=True
        ).order_by("-created_date")
        context["notifications"] = notifications
        return context


class NotificationFollowedQuestionsListView(LoginRequiredMixin, ListView):
    model = Notification
    login_url = "/users/login/"
    template_name = "notifications/notification_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        notifications = Notification.objects.filter(
            to_user=self.request.user.pk, is_followed_question=True
        ).order_by("-created_date")
        context["notifications"] = notifications
        return context


def dismiss_notification(request, pk=None):
    if request.user.is_authenticated:
        try:
            if pk is None:
                """dismiss all"""
                Notification.objects.filter(to_user=request.user.pk).delete()
                return JsonResponse({"dismiss_all": True, "success": True})
            else:
                Notification.objects.get(pk=pk).delete()
                return JsonResponse({"success": True})
        except:
            return JsonResponse({"success": False})

templates/notifications/base.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="sticky-top">
                <h6 class="text-muted">Your Notifications</h6>
                <hr>
                <h6 class="mb-3"><a href="{% url 'notifications:notifications_all' %}" class=" text-decoration-none">All
                        Notifications</a></h6>
                <h6 class="mb-3"><a href="{% url 'notifications:notifications_ans' %}"
                        class="text-decoration-none">Answers</a></h6>
                <h6 class="mb-3"><a href="{% url 'notifications:notifications_followed_questions' %}"
                        class="text-decoration-none">Followed
                        Questions</a></h6>
                <h6 class="mb-3"><a href="#" class="text-decoration-none">Questions Requests</a></h6>
                <hr>
                <div class="text-center">
                    <div class="h7 text-muted">
                        Made By <a href="https://github.com/MoulaHussainKhan">
                            Moula Hussain</a> and Rahul
                    </div>
                </div>
                <hr>
            </div>
        </div>
        <div class="col-md-9">
            <div class="text-right">
                <input type="button" value="Dismiss All" name="dismiss" class="btn btn-danger align-right" />
                <hr>
            </div>
            {% block notification %}{% endblock notification %}
        </div>
    </div>
</div>
{% endblock content %}

templates/notifications/notification_detail.html
{% extends "notifications/base.html" %}
{% load static %}
{% block title %}Notification Detail{% endblock title %}
{% block notification %}
<div class="col-md-9">
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="mr-2">
                        <img class="rounded-circle" width="45" height="45"
                            src="{% if question.user.display_img %}{{question.user.display_img.url}} {% else %} {% static 'imgs/no_display_img.jpg' %} {% endif %}">
                    </div>
                    <div class="ml-2">
                        <div class="p m-0">
                            <b>
                                <a href="{% url 'users:profile' question.user.slug %}" class="text-decoration-none">
                                    {{question.user.first_name | title}}
                                    {{question.user.last_name | title}}
                                </a>
                            </b> |
                            {{question.created_date |date:'d F, Y'}}
                        </div>
                        <div class="h7 text-muted">{{question.user.bio}}</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <a href="{% url 'qnA:question_detail' question.slug %}" target="_blank"
                class="card-link text-decoration-none">
                <b>
                    <h4 class="card-title crim">{{question}}</h4>
                </b>
            </a>
            <a href="{% url 'qnA:question_detail' question.slug %}" target="_blank"
                style="text-decoration: none; color:black;" class="text-decoration-none">
                <div class="ans">
                    {{ans.ans | safe | truncatewords_html:60}}
                </div>
            </a>
        </div>
        <div class=" card-footer">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex justify-content-between align-items-center">
                    {% if is_following_user_questions %}
                    <h4><a href="{% url 'qnA:answer' question.slug %}" class="text-decoration-none">Answer Now</a></h4>
                    {% elif not is_requested_question or is_following_user_answers %}
                    <div class="mr-2">
                        <img class="rounded-circle" width="45" height="45"
                            src="{% if ans.user.display_img %}{{ans.user.display_img.url}} {% else %} {% static 'imgs/no_display_img.jpg' %} {% endif %}">
                    </div>
                    <div class="ml-2">
                        <div class="p m-0">
                            {% if ans.is_anonymous %}
                            <i>Anonymous</i>
                            {% else %}
                            <b>
                                <a href="{% url 'users:profile' ans.user.slug %}" class="text-decoration-none">
                                    {{ans.user.first_name | title}}
                                    {{ans.user.last_name | title}}
                                </a>
                            </b> |
                            {{ans.created_date|date:'d F, Y'}}
                            {% if ans.created_date != ans.updated_date %}
                            (Edited)
                            {% endif %}
                            {% endif %}
                        </div>
                        <div class="h7 text-muted">{{ans.user.bio}}</div>
                    </div>
                    {% else %}
                    <h4><a href="{% url 'qnA:answer' question.slug %}" class="text-decoration-none">Answer Now</a></h4>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock notification %}

templates/notifications/notification_list.html
{% extends "notifications/base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css" />
{% endblock head %}
{% block title %}Notifications{% endblock title %}
{% block notification %}
{% if notifications %}
<div class="animate__animated dismiss-all">
    {% for notification in notifications %}
    <div class="animate__animated card mb-2 dismiss{{notification.pk}}" {% if notification.is_seen %}
        style="background-color: #F1F2F2;" {% endif %}>
        <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="mr-2">
                        {% if not notification.is_anonymous %}
                        <a href="{% url 'users:profile' notification.from_user.slug %}">
                            <img class="rounded-circle" width="45" height="45"
                                src="{% if notification.from_user.display_img %}{{notification.from_user.display_img.url}} {% else %} {% static 'imgs/no_display_img.jpg' %} {% endif %}">
                        </a>
                        {% else %}
                        <img class="rounded-circle" width="45" height="45" src="{% static 'imgs/no_display_img.jpg' %}">
                        {% endif %}
                    </div>
                    {% if notification.question %}
                    <a href="{% url 'notifications:notification_detail' notification.pk %}"
                        class="text-decoration-none read">
                        {% else %}
                        <a href="{% url 'users:profile' notification.from_user.slug %}"
                            class="text-decoration-none read">
                            {% endif %}
                            <div class="ml-2">
                                <div class="p m-0">
                                    <b>
                                        {{notification.msg}}
                                    </b>
                                </div>
                            </div>
                        </a>
                </div>
                <div>
                    <input type="button" value="Dismiss" name="dismiss" class="btn btn-outline-danger"
                        data-pk="{{notification.pk}}" />
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<h4 class="text-muted text-center">No Notifications</h4>
{% endif %}


{% if is_paginated %}
<div class="d-flex flex-row justify-content-center align-items-center">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item mr-2">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        <li class="page-item">
            <span>Page {{ page_obj.number }} of
                {{ page_obj.paginator.num_pages }}
            </span>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item ml-2">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}
{% endblock notification %}

{% block scripts %}
<script src="{% static 'js/dismiss_notifications.js' %}"></script>
{% endblock scripts %}