config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("qnA.urls", namespace="qnA")),
    path("users/", include("users.urls", namespace="users")),
    path("notifications/", include("notifications.urls", namespace="notifications")),
    path("summernote/", include("django_summernote.urls")),
    re_path(r"^comments/", include("django_comments_xtd.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

qnA/urls.py
from django.urls import path
from . import views

app_name = "qnA"
urlpatterns = [
    path("", views.QnaListView.as_view(), name="home"),
    path(
        "question/<slug:slug>/",
        views.QuestionDetailView.as_view(),
        name="question_detail",
    ),
    path(
        "question/request/<slug:slug>/",
        views.RequestAnswerListView.as_view(),
        name="answer_request",
    ),
    path(
        "question/request/<int:question_pk>/<int:user_pk>",
        views.request_answer,
        name="answer_request_ajax",
    ),
    # passing slugs for SEO purpose
    path(
        "question/<slug:slug>/answer/<slug:user_slug>/<int:question_pk>/<int:user_pk>",
        views.AnswerDetailView.as_view(),
        name="answer_detail",
    ),
    path("ask-question/", views.AskQuestionView.as_view(), name="ask-question"),
    path("answer/<slug:slug>", views.AnswerView.as_view(), name="answer"),
    path("answer/edit/<slug:slug>", views.AnswerUpdateView.as_view(), name="edit"),
    path("answer/delete/<slug:slug>", views.AnswerDeleteView.as_view(), name="delete"),
    path(
        "question/follow/<slug:question_slug>",
        views.follow_question,
        name="follow-question",
    ),
    path("<int:question_id>/vote", views.vote, name="question-vote"),
    path("question/<slug:slug>/<int:question_id>/vote/", views.vote, name="vote"),
    path("search/", views.QnaListView.as_view(), name="search"),
    path(
        "question/<slug:slug>/request/user/",
        views.RequestAnswerListView.as_view(),
        name="search-user",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("profile/<slug:slug>", views.ProfileDetailView.as_view(), name="profile"),
    path(
        "profile/<slug:slug>/questions",
        views.ProfileQuestionListView.as_view(),
        name="profile_questions",
    ),
    path(
        "profile/<slug:slug>/answers",
        views.ProfileAnswerListView.as_view(),
        name="profile_answers",
    ),
    path(
        "profile/<slug:slug>/answers/<str:is_pin>/<int:answer_pk>",
        views.profile_answer_pin,
        name="is_pin_answer",
    ),
    path(
        "profile/<slug:slug>/followers",
        views.ProfileFollowersListView.as_view(),
        name="followers",
    ),
    path(
        "profile/<slug:slug>/following",
        views.ProfileFollowingListView.as_view(),
        name="following",
    ),
    path("edit/", views.ProfileUpdateView.as_view(), name="edit"),
    path("add/workplace/", views.WorkPlaceFormAddView.as_view(), name="workplace_add"),
    path("edit/workplace/", views.WorkPlaceUpdateView.as_view(), name="workplace_edit"),
    path("delete/workplace/", views.delete_workplace, name="workplace_delete"),
    path("add/education/", views.EducationFormAddView.as_view(), name="education_add"),
    path("edit/education/", views.EducationUpdateView.as_view(), name="education_edit"),
    path("delete/education/", views.delete_education, name="education_delete",),
    path(
        "follow_toggle/<slug:slug>",
        views.follow_unfollow_users,
        name="follow_unfollow",
    ),
    path("logout/", views.logout_request, name="logout"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
]

qnA/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from autoslug import AutoSlugField
from vote.models import VoteModel
from users import models as userModels


class Topic(models.Model):

    topic = models.CharField(max_length=255)

    def __str__(self):
        return self.topic


class Question(VoteModel, models.Model):
    title = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from="title", unique=True)
    user = models.ForeignKey(userModels.User, on_delete=models.CASCADE)
    is_anonymous = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    topics = models.ManyToManyField(Topic, blank=True)
    rank = models.FloatField(default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    # class Meta:
    #     ordering = ["-vote_score"]


class Answer(VoteModel, models.Model):
    class Meta:
        ordering = ["-vote_score"]

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    ans = models.TextField()
    user = models.ForeignKey(userModels.User, on_delete=models.CASCADE)
    is_anonymous = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    pin_answer = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("qnA:question_detail", kwargs={"slug": self.question.slug,},)

    def __str__(self):
        return f"{self.user.first_name} on {self.created_date}"


class FollowQuestion(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="follow_question",
    )
    user = models.ForeignKey(
        userModels.User, on_delete=models.CASCADE, related_name="follow_question_by"
    )

qnA/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = [
            "title",
            "is_anonymous",
        ]
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "class": "form-control input-lg",
                    "placeholder": "What is your question?",
                    "style": "height: 70px;",
                }
            ),
        }
        labels = {"title": "", "is_anonymous": "Ask Anonymously"}


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = [
            "ans",
            "is_anonymous",
        ]
        widgets = {
            "ans": SummernoteWidget(),
        }
        labels = {"ans": "", "is_anonymous": "Answer Anonymously"}

qnA/views.py
import math
from datetime import datetime
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.http import JsonResponse, Http404
from django.views.generic import ListView, DetailView, FormView, UpdateView, DeleteView
from django.utils import timezone
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from comments.models import MyComment
from .models import *
from .forms import *
from .get_topics import *
from users.models import User, Follow
from notifications.models import Notification


class QnaListView(ListView):
    model = Question
    template_name = "qnA/qnA_list.html"
    paginate_by = 10
    context_object_name = "questions"

    def get_queryset(self):
        try:
            question = self.request.GET.get("question")
            questions = Question.objects.filter(title__icontains=question)
        except:
            questions = Question.objects.all()
        for question in questions:
            order = math.log(max(abs(question.vote_score), 1), 10)
            if question.vote_score > 0:
                sign = 1
            elif question.vote_score < 0:
                sign = -1
            else:
                sign = 0
            seconds = (question.created_date).timestamp() - 1134028003
            question.rank = round(sign * order + seconds / 10800, 7)
        sorted_submissions = sorted(questions, key=lambda x: x.rank, reverse=True)
        paginator = Paginator(sorted_submissions, self.paginate_by)
        page = self.request.GET.get("page")
        try:
            pagin = paginator.page(page)
        except PageNotAnInteger:
            pagin = paginator.page(1)
        except EmptyPage:
            pagin = paginator.page(paginator.num_pages)
        return sorted_submissions


class QuestionDetailView(DetailView):
    queryset = Question.objects.all()

    def get_context_data(self, **kwargs):
        context = super(QuestionDetailView, self).get_context_data(**kwargs)
        topics = self.get_object().topics.all()
        related_questions = []
        max_matches = False
        for topic in topics:
            matches = Question.objects.filter(title__icontains=topic).exclude(
                pk=self.get_object().pk
            )
            for match in matches:
                if len(related_questions) != 8 and match not in related_questions:
                    related_questions.append(match)
                else:
                    max_matches = True
                    break
            if max_matches:
                break
        is_following = FollowQuestion.objects.filter(
            user=self.request.user.pk, question=self.get_object()
        )
        try:
            """this is in try/except block otherwise it'll throw error when a user who isn't logged in visits a question detail page"""
            is_answered = self.get_object().answer_set.filter(user=self.request.user)
            context["is_answered"] = is_answered
        except:
            pass
        context["is_following"] = is_following
        context["related_questions"] = related_questions
        return context


class AskQuestionView(LoginRequiredMixin, FormView):
    login_url = "/users/login/"
    template_name = "qnA/qnA.html"
    form_class = QuestionForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        question = form.save(commit=False)
        question.user = self.request.user
        question_topics = get_topics(question.title)
        question.save()
        for topic in question_topics:
            if not Topic.objects.filter(topic=topic).exists():
                Topic.objects.create(topic=topic)
            question.topics.add(Topic.objects.get(topic=topic))
        if not question.is_anonymous:
            followers = Follow.objects.filter(to_user=self.request.user)
            for follower in followers:
                Notification.objects.create(
                    from_user=self.request.user,
                    to_user=follower.from_user,
                    msg=f"{self.request.user.first_name} {self.request.user.last_name} asked a question: {question.title}",
                    question=question,
                    is_following_user_questions=True,
                )
        return redirect(reverse("qnA:question_detail", kwargs={"slug": question.slug}))


class AnswerView(LoginRequiredMixin, FormView):
    login_url = "/users/login/"
    template_name = "qnA/qnA.html"
    form_class = AnswerForm

    def form_valid(self, form):
        question_slug = self.kwargs.get("slug")
        question = Question.objects.get(slug=question_slug)
        answer = form.save(commit=False)
        answer.user = self.request.user
        answer.question = question
        answer.save()
        if not answer.is_anonymous:
            followers = Follow.objects.filter(to_user=self.request.user)
            for follower in followers:
                if follower.from_user != question.user:
                    Notification.objects.create(
                        from_user=self.request.user,
                        to_user=follower.from_user,
                        msg=f"{self.request.user.first_name} {self.request.user.last_name} answered a question: {question.title}",
                        question=question,
                        is_following_user_answers=True,
                    )
        return redirect(reverse("qnA:question_detail", kwargs={"slug": question_slug}))

    def get_context_data(self, **kwargs):
        context = super(AnswerView, self).get_context_data(**kwargs)
        question_slug = self.kwargs.get("slug")
        question = Question.objects.get(slug=question_slug)
        context["question"] = question
        return context

    def dispatch(self, request, *args, **kwargs):
        """redirect to edit answer url if answer of the user already exists"""
        question_slug = self.kwargs.get("slug")
        question = Question.objects.get(slug=question_slug)
        try:
            Answer.objects.get(question=question, user=request.user)
            return redirect(reverse("qnA:edit", kwargs={"slug": question_slug}))
        except:
            pass
        return super(AnswerView, self).dispatch(request, *args, **kwargs)


class AnswerDetailView(DetailView):
    queryset = Question.objects.all()
    template_name = "qnA/answer_detail.html"

    def get_context_data(self, **kwargs):
        context = super(AnswerDetailView, self).get_context_data(**kwargs)
        question_pk = self.kwargs.get("question_pk")
        user_pk = self.kwargs.get("user_pk")
        question = Question.objects.get(pk=question_pk)
        user_answer = question.answer_set.get(user=user_pk)
        context["user_answer"] = user_answer
        return context


class AnswerUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "qnA/qnA.html"
    model = Question
    form_class = AnswerForm
    login_url = "/users/login/"

    def get_object(self, queryset=None):
        question = super().get_object(queryset=queryset)
        try:
            ans = question.answer_set.get(user=self.request.user)
            return ans
        except:
            raise Http404

    def get_success_url(self, **kwargs):
        return reverse_lazy(
            "qnA:answer_detail",
            args=(
                self.object.question.slug,
                self.object.user.slug,
                self.object.question.pk,
                self.object.user.pk,
            ),
        )


class AnswerDeleteView(LoginRequiredMixin, DeleteView):
    model = Question
    login_url = "/users/login/"

    def get_object(self, queryset=None):
        question = super().get_object(queryset=queryset)
        try:
            ans = question.answer_set.get(user=self.request.user)
            return ans
        except:
            raise Http404

    def get_success_url(self, **kwargs):
        return reverse_lazy("qnA:question_detail", args=(self.object.question.slug,))


class RequestAnswerListView(LoginRequiredMixin, ListView):
    model = Question
    template_name = "qnA/answer_request.html"
    login_url = "/users/login/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question_slug = self.kwargs["slug"]
        question = Question.objects.get(slug=question_slug)
        try:
            searched_user = self.request.GET.get("user")
            try:
                first_name, *_, last_name = searched_user.split()
                users_list = User.objects.filter(
                    first_name__contains=first_name, last_name__contains=last_name
                )
            except:
                """ only one name entered """
                users_list = User.objects.filter(
                    Q(first_name__contains=searched_user)
                    | Q(last_name__contains=searched_user)
                )
            user_l = {}
            for user in users_list:
                is_requested_question = Notification.objects.filter(
                    from_user=self.request.user.pk,
                    to_user=user.pk,
                    question=question,
                    is_requested_question=True,
                )
                user_l[user] = is_requested_question

            context["user_l"] = user_l
        except:
            answer_users = []
            for answer in question.answer_set.all():
                answer_users.append(answer.user)
            question_topics = question.topics.all()
            suggested_users = {}
            for topic in question_topics:
                """find similar questions"""
                matches = Question.objects.filter(title__icontains=topic).exclude(
                    slug=question_slug

templates/qnA/answer_confirm_delete.html
{% extends "users/login_and_register.html" %}
{% block title %}Are You Sure You Want to Delete?{% endblock title %}
{% block img %}
{% endblock img %}
{% block form %}
<form method="post">
    {% csrf_token %}
    <h5 class="text-muted">Are you sure you want to delete your Answer?</h5>
    {% block btn %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-light" href="{% url 'qnA:question_detail' object.question.slug %}">No</a>
    {% endblock btn %}
</form>
{% endblock form %}
{% block msg %}{% endblock msg %}
{% block footer %} {% endblock footer %}

templates/qnA/qnA.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if question %}
Answer {{question}}
{% else %}
Ask Question
{% endif %}
{% endblock title %}
{% block content %}
{% if messages %}
{% for message in messages %}
<div class="text-center alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Uh, oh!</strong> {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="card" style="background-color: #F1F2F2;">
                {% if user.is_authenticated %}
                <div class="card-body text-center">
                    <img class="rounded-circle text-center" height="100" width="100"
                        src="{% if request.user.display_img %}{{request.user.display_img.url}} {% else %} {% static 'imgs/no_display_img.jpg' %} {% endif %}">
                    <div class="h5 mt-2 mb-0"><a href="{% url 'users:profile' user.slug %}">{{user.first_name}}
                            {{user.last_name}}</a></div>
                    <div class="h7 text-muted">{{user.bio}}</div>
                    <a class="btn btn-outline-danger mt-2" href="{% url 'users:edit' %}" role="button">Edit Profile</a>
                </div>
                {% endif %}
            </div>
            <div class="text-center mt-4 sticky-top">
                <div class="h7 text-muted">
                    Made By <a href="https://github.com/MoulaHussainKhan">
                        Moula Hussain</a> and Rahul
                </div>
            </div>
        </div>
        <div class="col-md-9">

            {% if question %}
            <h3 class="crim">{{question}}</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Submit" class="btn btn-danger">
            </form>
            {% else %}
            <div class="card mb-2">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Submit" class="btn btn-danger">
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/qnA/question_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load comments %}
{% load comments_xtd %}
{% block title %}{{question.title}}{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="related-questions sticky-top">
                <h6>Related Questions</h6>
                <hr>
                {% for question in related_questions %}
                <div class="question mb-3">
                    <a href="{% url 'qnA:question_detail' question.slug %}" target="_blank" class="card-link">
                        <h6>{{question}}</h6>
                    </a>
                </div>
                {% endfor %}

                <div class="text-center">
                    <div class="h7 text-muted">
                        Made By <a href="https://github.com/MoulaHussainKhan">
                            Moula Hussain</a> and Rahul
                    </div>
                </div>
                <hr>
            </div>
        </div>
        <div class="col-md-9">
            <div class="question">
                <h3 class="crim">{{question}}</h3>
                <h6>
                    <b>{{question.answer_set.count}} Answers</b> |
                    {% if not is_answered %}
                    <a href="{% url 'qnA:answer' question.slug %}" class="badge badge-danger"><img
                            src="{% static 'imgs/qnA/pencil-square.svg' %}" alt="Answer">
                        Answer</a>
                    {% else %}
                    <a href="{% url 'qnA:edit' question.slug %}" class="badge badge-primary"><img
                            src="{% static 'imgs/qnA/pencil-square.svg' %}" alt="Edit">
                        Edit Answer</a> |
                    <a href="{% url 'qnA:delete' question.slug %}" class="badge badge-dark"><img
                            src="{% static 'imgs/qnA/pencil-square.svg' %}" alt="Delete">
                        Delete Answer</a>
                    {% endif %}
                    |
                    {% if question.user != user %}
                    {% if is_following %}
                    <a id="follow" href="{% url 'qnA:follow-question' question.slug %}" class="badge badge-info">
                        Unfollow Question</a>
                    {% else %}
                    <a id="follow" href="{% url 'qnA:follow-question' question.slug %}" class="badge badge-danger">
                        Follow Question</a>
                    {% endif %} |
                    {% endif %}
                    <a href="{% url 'qnA:answer_request' question.slug %}" class="badge badge-primary">
                        Request Answer</a>
                </h6>
            </div>
            <hr>
            {% if question.answer_set.count == 0 %}
            <h4 class="text-center">No Answers</h4>
            {% else %}
            {% for answer in question.answer_set.all %}
            <div class="card gedf-card mb-4">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="mr-2">
                                {% if not answer.is_anonymous %}
                                <a href="{% url 'users:profile' answer.user.slug %}">
                                    <img class="rounded-circle" width="45" height="45"
                                        src="{% if answer.user.display_img %}{{answer.user.display_img.url}} {% else %} {% static 'imgs/no_display_img.jpg' %} {% endif %}">
                                </a>
                                {% else %}
                                <img class="rounded-circle" width="45" height="45"
                                    src="{% static 'imgs/no_display_img.jpg' %}">
                                {% endif %}
                            </div>
                            <div class="ml-2">
                                <div class="p m-0">
                                    {% if answer.is_anonymous %}
                                    <i>Anonymous</i>
                                    {% else %}
                                    <b>
                                        <a href="{% url 'users:profile' answer.user.slug %}"
                                            class="text-decoration-none">
                                            {{answer.user.first_name | title}} {{answer.user.last_name | title}}
                                        </a>
                                    </b>
                                    {% endif %}
                                    |
                                    {{answer.created_date |date:'d F, Y'}}
                                    {% if answer.created_date != answer.updated_date %}
                                    (Edited)
                                    {% endif %}
                                </div>
                                {% if not answer.is_anonymous %}
                                <div class="h7 text-muted">{{answer.user.bio}}</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="ans">
                        {{answer.ans | safe}}
                    </div>
                </div>
                {% if question.answer_set.all.0.ans %}
                <div class="card-footer">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <h4 id="score{{answer.pk}}">{{answer.vote_score}}</h4>
                                <div class="score-form" data-pk="{{answer.pk}}"
                                    data-page="{% if page_obj.number %}{{page_obj.number }}{% endif %}">
                                    <input type="image" value="Up" name="up" class="Up{{answer.pk}} upvote" id="upvote"
                                        data-pk="{{answer.pk}}" src="{% static 'imgs/qnA/caret-up-square.svg' %}" />
                                    <input type="image" value="Down" name="down" class="Down{{answer.pk}} downvote"
                                        data-pk="{{answer.pk}}" src="{% static 'imgs/qnA/caret-down-square.svg' %}" />
                                </div>
                            </div>
                        </div>
                        <div>
                            <div style="background-color: #d7dddd;" class="rounded">
                                <div class="dropdown">
                                    <button class="btn btn-link dropdown-toggle" type="button" data-toggle="dropdown">
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item"
                                            href="{% url 'qnA:answer_detail' answer.question.slug answer.user.slug answer.question.pk answer.user.pk %}">Share
                                            Answer</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div id="comments">
                        {% if user.pk %}
                        <div class="comment">
                            <H4 class="text-center">Post your comment</H4>
                            <div class="well">
                                {% render_comment_form for answer %}
                            </div>
                        </div>
                        {% else %}
                        <a href="{% url 'users:login' %}">Login to Comment</a>
                        {% endif %}
                        {% get_comment_count for answer as comment_count %}
                        {% if comment_count %}
                        <H5 class="text-center">
                            {% blocktrans count comment_count=comment_count %}
                            There is {{ comment_count }} comment below.
                            {% plural %}
                            There are {{ comment_count }} comments below.
                            {% endblocktrans %}
                        </H5>
                        {% endif %}

                        {% if comment_count %}
                        <hr />
                        <ul class="media-list" id="comment-list">
                            {% render_xtdcomment_tree for answer %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
                {% else %}
                <div class="card-footer">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="ml-2">
                                <h4><a href="{% url 'qnA:answer' question.slug %}">Answer Now</a></h4>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
<hr>
{% endblock %}
{% block scripts %}
<script src="{% static 'js/vote.js' %}"></script>
<script src="{% static 'js/follow_toggler.js' %}"></script>
{% endblock scripts %}