config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("qnA.urls", namespace="qnA")),
    path("users/", include("users.urls", namespace="users")),
    path("notifications/", include("notifications.urls", namespace="notifications")),
    path("summernote/", include("django_summernote.urls")),
    re_path(r"^comments/", include("django_comments_xtd.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

notifications/urls.py
from django.urls import path
from . import views

app_name = "notifications"
urlpatterns = [
    path("all/", views.NotificationListView.as_view(), name="notifications_all",),
    path(
        "answers/",
        views.NotificationAnswerListView.as_view(),
        name="notifications_ans",
    ),
    path(
        "followed-questions/",
        views.NotificationFollowedQuestionsListView.as_view(),
        name="notifications_followed_questions",
    ),
    path(
        "<int:pk>", views.NotificationDetailView.as_view(), name="notification_detail",
    ),
    path("dismiss/all", views.dismiss_notification, name="dismiss_all_notification",),
    path("dismiss/<int:pk>", views.dismiss_notification, name="dismiss_notification",),
]

qnA/urls.py
from django.urls import path
from . import views

app_name = "qnA"
urlpatterns = [
    path("", views.QnaListView.as_view(), name="home"),
    path(
        "question/<slug:slug>/",
        views.QuestionDetailView.as_view(),
        name="question_detail",
    ),
    path(
        "question/request/<slug:slug>/",
        views.RequestAnswerListView.as_view(),
        name="answer_request",
    ),
    path(
        "question/request/<int:question_pk>/<int:user_pk>",
        views.request_answer,
        name="answer_request_ajax",
    ),
    # passing slugs for SEO purpose
    path(
        "question/<slug:slug>/answer/<slug:user_slug>/<int:question_pk>/<int:user_pk>",
        views.AnswerDetailView.as_view(),
        name="answer_detail",
    ),
    path("ask-question/", views.AskQuestionView.as_view(), name="ask-question"),
    path("answer/<slug:slug>", views.AnswerView.as_view(), name="answer"),
    path("answer/edit/<slug:slug>", views.AnswerUpdateView.as_view(), name="edit"),
    path("answer/delete/<slug:slug>", views.AnswerDeleteView.as_view(), name="delete"),
    path(
        "question/follow/<slug:question_slug>",
        views.follow_question,
        name="follow-question",
    ),
    path("<int:question_id>/vote", views.vote, name="question-vote"),
    path("question/<slug:slug>/<int:question_id>/vote/", views.vote, name="vote"),
    path("search/", views.QnaListView.as_view(), name="search"),
    path(
        "question/<slug:slug>/request/user/",
        views.RequestAnswerListView.as_view(),
        name="search-user",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("profile/<slug:slug>", views.ProfileDetailView.as_view(), name="profile"),
    path(
        "profile/<slug:slug>/questions",
        views.ProfileQuestionListView.as_view(),
        name="profile_questions",
    ),
    path(
        "profile/<slug:slug>/answers",
        views.ProfileAnswerListView.as_view(),
        name="profile_answers",
    ),
    path(
        "profile/<slug:slug>/answers/<str:is_pin>/<int:answer_pk>",
        views.profile_answer_pin,
        name="is_pin_answer",
    ),
    path(
        "profile/<slug:slug>/followers",
        views.ProfileFollowersListView.as_view(),
        name="followers",
    ),
    path(
        "profile/<slug:slug>/following",
        views.ProfileFollowingListView.as_view(),
        name="following",
    ),
    path("edit/", views.ProfileUpdateView.as_view(), name="edit"),
    path("add/workplace/", views.WorkPlaceFormAddView.as_view(), name="workplace_add"),
    path("edit/workplace/", views.WorkPlaceUpdateView.as_view(), name="workplace_edit"),
    path("delete/workplace/", views.delete_workplace, name="workplace_delete"),
    path("add/education/", views.EducationFormAddView.as_view(), name="education_add"),
    path("edit/education/", views.EducationUpdateView.as_view(), name="education_edit"),
    path("delete/education/", views.delete_education, name="education_delete",),
    path(
        "follow_toggle/<slug:slug>",
        views.follow_unfollow_users,
        name="follow_unfollow",
    ),
    path("logout/", views.logout_request, name="logout"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
]

templates/base.html
{% load static %}
{% load notifications %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block head %}{% endblock head %}
  <title>{% block title %}{% endblock title %}</title>
</head>

<body style="background-color: #F1F2F2;">
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color: #f8f9fa;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'qnA:home' %}">
        <img src="{% static 'imgs/logo.png' %}" height="65" loading="lazy">
      </a> 
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto ml-auto">
          <li class="nav-item">
            <form class="form-inline my-2 my-lg-0" action="{% url 'qnA:search' %}" method="get">
              <input class="form-control mr-sm-2" type="search" placeholder="Search Questions" name="question"
                value="{{request.GET.question}}" required>
              <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
            </form>
          </li>
        </ul>
        {% block buttons %}
        {% if request.user.is_authenticated %}
        <div class="item">
          <a class="mr-4 btn btn-light " href="{% url 'notifications:notifications_all' %}">
            <span class="notify-badge">{% unread_notification request.user %}</span>
            Notifications
          </a>
        </div>
        <a class="btn btn-danger mr-4" href="{% url 'qnA:ask-question' %}" role="button">Ask Question</a>
        <a class="btn btn-danger" href="{% url 'users:logout' %}" role="button">Logout</a>
        {% else %}
        <a class="btn btn-danger mr-4" href="{% url 'users:login' %}" role="button">Login</a>
        <a class="btn btn-danger" href="{% url 'users:register' %}" role="button">Register</a>
        {% endif %}
        {% endblock buttons %}

      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  {% block scripts %}
  {% endblock scripts %}
</body>

</html>