config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("qnA.urls", namespace="qnA")),
    path("users/", include("users.urls", namespace="users")),
    path("notifications/", include("notifications.urls", namespace="notifications")),
    path("summernote/", include("django_summernote.urls")),
    re_path(r"^comments/", include("django_comments_xtd.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

qnA/urls.py
from django.urls import path
from . import views

app_name = "qnA"
urlpatterns = [
    path("", views.QnaListView.as_view(), name="home"),
    path(
        "question/<slug:slug>/",
        views.QuestionDetailView.as_view(),
        name="question_detail",
    ),
    path(
        "question/request/<slug:slug>/",
        views.RequestAnswerListView.as_view(),
        name="answer_request",
    ),
    path(
        "question/request/<int:question_pk>/<int:user_pk>",
        views.request_answer,
        name="answer_request_ajax",
    ),
    # passing slugs for SEO purpose
    path(
        "question/<slug:slug>/answer/<slug:user_slug>/<int:question_pk>/<int:user_pk>",
        views.AnswerDetailView.as_view(),
        name="answer_detail",
    ),
    path("ask-question/", views.AskQuestionView.as_view(), name="ask-question"),
    path("answer/<slug:slug>", views.AnswerView.as_view(), name="answer"),
    path("answer/edit/<slug:slug>", views.AnswerUpdateView.as_view(), name="edit"),
    path("answer/delete/<slug:slug>", views.AnswerDeleteView.as_view(), name="delete"),
    path(
        "question/follow/<slug:question_slug>",
        views.follow_question,
        name="follow-question",
    ),
    path("<int:question_id>/vote", views.vote, name="question-vote"),
    path("question/<slug:slug>/<int:question_id>/vote/", views.vote, name="vote"),
    path("search/", views.QnaListView.as_view(), name="search"),
    path(
        "question/<slug:slug>/request/user/",
        views.RequestAnswerListView.as_view(),
        name="search-user",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("profile/<slug:slug>", views.ProfileDetailView.as_view(), name="profile"),
    path(
        "profile/<slug:slug>/questions",
        views.ProfileQuestionListView.as_view(),
        name="profile_questions",
    ),
    path(
        "profile/<slug:slug>/answers",
        views.ProfileAnswerListView.as_view(),
        name="profile_answers",
    ),
    path(
        "profile/<slug:slug>/answers/<str:is_pin>/<int:answer_pk>",
        views.profile_answer_pin,
        name="is_pin_answer",
    ),
    path(
        "profile/<slug:slug>/followers",
        views.ProfileFollowersListView.as_view(),
        name="followers",
    ),
    path(
        "profile/<slug:slug>/following",
        views.ProfileFollowingListView.as_view(),
        name="following",
    ),
    path("edit/", views.ProfileUpdateView.as_view(), name="edit"),
    path("add/workplace/", views.WorkPlaceFormAddView.as_view(), name="workplace_add"),
    path("edit/workplace/", views.WorkPlaceUpdateView.as_view(), name="workplace_edit"),
    path("delete/workplace/", views.delete_workplace, name="workplace_delete"),
    path("add/education/", views.EducationFormAddView.as_view(), name="education_add"),
    path("edit/education/", views.EducationUpdateView.as_view(), name="education_edit"),
    path("delete/education/", views.delete_education, name="education_delete",),
    path(
        "follow_toggle/<slug:slug>",
        views.follow_unfollow_users,
        name="follow_unfollow",
    ),
    path("logout/", views.logout_request, name="logout"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
]

qnA/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from autoslug import AutoSlugField
from vote.models import VoteModel
from users import models as userModels


class Topic(models.Model):

    topic = models.CharField(max_length=255)

    def __str__(self):
        return self.topic


class Question(VoteModel, models.Model):
    title = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from="title", unique=True)
    user = models.ForeignKey(userModels.User, on_delete=models.CASCADE)
    is_anonymous = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    topics = models.ManyToManyField(Topic, blank=True)
    rank = models.FloatField(default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    # class Meta:
    #     ordering = ["-vote_score"]


class Answer(VoteModel, models.Model):
    class Meta:
        ordering = ["-vote_score"]

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    ans = models.TextField()
    user = models.ForeignKey(userModels.User, on_delete=models.CASCADE)
    is_anonymous = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    pin_answer = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("qnA:question_detail", kwargs={"slug": self.question.slug,},)

    def __str__(self):
        return f"{self.user.first_name} on {self.created_date}"


class FollowQuestion(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="follow_question",
    )
    user = models.ForeignKey(
        userModels.User, on_delete=models.CASCADE, related_name="follow_question_by"
    )

users/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from autoslug import AutoSlugField


class User(AbstractUser):
    bio = models.TextField(default="")
    display_img = models.ImageField(blank=True, upload_to="users")
    slug = AutoSlugField(populate_from="first_name", unique=True)
    location = models.CharField(max_length=100, blank=True)

    def save(self, *args, **kwargs):
        full_name = self.first_name + "-" + self.last_name
        self.slug = slugify(full_name)
        super(User, self).save(*args, **kwargs)


class Follow(models.Model):
    from_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="from_people"
    )
    to_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="to_people"
    )

    def __str__(self):
        return f"{self.from_user} follows {self.to_user}"


YEAR_CHOICES = []
for year in range(1980, (datetime.datetime.now().year + 1)):
    YEAR_CHOICES.append((year, year))


class WorkPlace(models.Model):
    company_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    start_year = models.IntegerField(choices=YEAR_CHOICES, null=True, blank=True,)
    end_year = models.IntegerField(choices=YEAR_CHOICES, null=True, blank=True,)
    is_currently_working = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.company_name


class Education(models.Model):
    school_name = models.CharField(max_length=100)
    start_year = models.IntegerField(choices=YEAR_CHOICES, null=True, blank=True,)
    end_year = models.IntegerField(choices=YEAR_CHOICES, null=True, blank=True,)
    is_currently_studying = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.school_name

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core import validators
from django import forms
from .models import User, WorkPlace, Education


class LoginForm(forms.Form):
    email = forms.EmailField(
        label="Enter Email",
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter Email"}
        ),
    )
    password = forms.CharField(
        label="Enter password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Enter Password"}
        ),
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = User.objects.get(username=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password Incorrect"))
        except:
            self.add_error("email", forms.ValidationError("User Doesn't Exist"))

        return email

    def save(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")


class RegisterForm(forms.Form):
    first_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter First Name"}
        ),
    )
    last_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter Last Name"}
        ),
    )
    email = forms.EmailField(
        label="Enter email",
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter Email"}
        ),
    )
    password = forms.CharField(
        label="Enter password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Enter Password"}
        ),
        validators=[validate_password],
    )
    password1 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Confirm Password"}
        ),
        validators=[validate_password],
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            User.objects.get(email=email)
            raise forms.ValidationError("User Already exists")
        except User.DoesNotExist:
            return email

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        password = self.cleaned_data.get("password")
        if password1 != password:
            raise forms.ValidationError(
                "Password and Confirmation Password does not match."
            )
        else:
            return password1

    def save(self):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        createdUser = User.objects.create_user(email, email, password)
        createdUser.first_name = first_name
        createdUser.last_name = last_name
        createdUser.save()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "bio",
            "location",
            "display_img",
        )
        widgets = {
            "first_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter First Name"}
            ),
            "last_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter Last Name"}
            ),
            "location": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter Location"}
            ),
            "bio": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Enter Bio", "rows": 3,}
            ),
        }


class WorkPlaceForm(forms.ModelForm):
    class Meta:
        model = WorkPlace
        fields = (
            "company_name",
            "position",
            "start_year",
            "end_year",
            "is_currently_working",
        )
        widgets = {
            "company_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter Company Name"}
            ),
            "position": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter Your Position"}
            ),
            "start_year": forms.Select(attrs={"class": "form-control",}),
            "end_year": forms.Select(attrs={"class": "form-control",}),
        }
        labels = {
            "is_currently_working": "Currently Working",
        }


class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = (
            "school_name",
            "start_year",
            "end_year",
            "is_currently_studying",
        )
        widgets = {
            "school_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter School Name"}
            ),
            "start_year": forms.Select(attrs={"class": "form-control",}),
            "end_year": forms.Select(attrs={"class": "form-control",}),
        }
        labels = {
            "is_currently_studying": "Currently Studying",
        }

templates/users/base_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-9 mt-5">
            <div class="card gedf-card">
                <div class="card-body text-center">
                    {% block edit_form %}{% endblock edit_form %}
                </div>
            </div>
            <p class="text-muted text-center mt-4">Made By <a href="https://github.com/MoulaHussainKhan">
                Moula Hussain</a> and Rahul
            </p>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/edit.html
{% extends "users/base_form.html" %}
{% load static %}
{% block title %}
{% if is_profile_update %}
Edit Profile
{% else %}
Edit Credentials and Highlights
{% endif %}
{% endblock title %}
{% block edit_form %}
{% if is_profile_update %}
<img class="rounded-circle" height="100" width="100"
    src="{% if request.user.display_img %}{{request.user.display_img.url}} {% else %} {% static 'imgs/no_display_img.jpg' %} {% endif %}">
{% endif %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    {% if is_profile_update %}
    <button class="btn btn-lg btn-danger btn-block">Update Profile</button>
    {% else %}
    <button class="btn btn-lg btn-danger btn-block">Update WorkPlace Details</button>
    {% endif %}
</form>
</p>
{% endblock edit_form %}

templates/users/login.html
{% extends "users/login_and_register.html" %}
{% block title %}Login{% endblock title %}
{% block btn %}
<button class="btn btn-lg btn-danger btn-block">Sign in</button>
{% endblock btn %}
{% block msg %}
<p class="mt-2 mb-3">Don't have an account? <a href="{% url 'users:register' %}">Register</a>
</p>
{% endblock msg %}

templates/users/register.html
{% extends "users/login_and_register.html" %}
{% block title %}Register{% endblock title %}
{% block btn %}
<button class="btn btn-lg btn-danger btn-block">Register</button>
{% endblock btn %}
{% block msg %}
<p class="mt-2 mb-3">Already have an account? <a href="{% url 'users:login' %}">Login</a>
</p>
{% endblock msg %}

templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{user.first_name | title}} {{user.last_name | title}}'s Profile{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="d-flex flex-row justify-content-center">
                <div>
                    <img class="rounded-circle text-center mr-4" height="100" width="100"
                        src="{% if user.display_img %}{{user.display_img.url}} {% else %} {% static 'imgs/no_display_img.jpg' %} {% endif %}">
                </div>
                <div class="align-self-center">
                    <h1 class="crim">{{user.first_name | title}} {{user.last_name | title}}</h1>
                    <h6 class="text-muted">{{user.bio}}</h6>
                </div>
                <hr>
                <div class="align-self-center">
                    {% if request.user != user %}
                    {% if is_following %}
                    <a class="btn btn-outline-danger mr-4" href="{% url 'users:follow_unfollow' user.slug %}"
                        role="button" id="follow">Unfollow</a>
                    {% else %}
                    <a class="btn btn-danger mr-4" href="{% url 'users:follow_unfollow' user.slug %}" role="button"
                        id="follow">Follow</a>
                    {% endif %}
                    {% endif %}
                </div>

            </div>
            <hr>
            <div class="links">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link btn-outline-danger" href="{% url 'users:profile' user.slug %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-danger"
                            href="{% url 'users:profile_questions' user.slug %}">Questions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-danger"
                            href="{% url 'users:profile_answers' user.slug %}">Answers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-danger"
                            href="{% url 'users:followers' user.slug %}">Followers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-danger"
                            href="{% url 'users:following' user.slug %}">Following</a>
                    </li>
                </ul>
            </div>
            <hr>
            {% block profile %}
            {% if answers %}
            <h4 class="crim text-center mb-4">{{user.first_name | title}} {{user.last_name | title}}'s Pinned Answers
            </h4>
            <div class="user-profile">
                {% for answer in answers %}

                {% if not answer.is_anonymous %}
                <div class="card mb-4">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="mr-2">
                                    <img class="rounded-circle" width="45" height="45"
                                        src="{% if answer.question.user.display_img %}{{answer.question.user.display_img.url}} {% else %} {% static 'imgs/no_display_img.jpg' %} {% endif %}">
                                </div>
                                <div class="ml-2">
                                    <div class="p m-0">
                                        <a href="{% url 'users:profile' answer.question.user.slug %}"
                                            class="text-decoration-none">
                                            <b>
                                                {{answer.question.user.first_name | title}}
                                                {{answer.question.user.last_name | title}}
                                            </b>
                                        </a> |
                                        {{answer.question.created_date |date:'d F, Y'}}
                                    </div>
                                    <div class="h7 text-muted">{{answer.question.user.bio}}</div>
                                </div>
                            </div>
                            <div>
                                <h4 id="score{{answer.question.pk}}">{{answer.question.vote_score}}</h4>
                                <div class="score-form" data-pk="{{answer.question.pk}}" data-profile="True">
                                    <input type="image" value="Up" name="up" class="Up{{answer.question.pk}} upvote"
                                        id="upvote" data-pk="{{answer.question.pk}}" data-profile="True"
                                        src="{% static 'imgs/qnA/caret-up-square.svg' %}" />
                                    <input type="image" value="Down" name="down"
                                        class="Down{{answer.question.pk}} downvote" data-pk="{{answer.question.pk}}"
                                        data-profile="True" src="{% static 'imgs/qnA/caret-down-square.svg' %}" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'qnA:question_detail' answer.question.slug %}" target="_blank"
                            class="card-link">
                            <b>
                                <h4 class="card-title crim">{{answer.question}}</h4>
                            </b>
                        </a>
                        <a href="{% url 'qnA:question_detail' answer.question.slug %}" target="_blank"
                            style="text-decoration: none; color:black;">
                            <div class="ans">
                                {{answer.ans | safe | truncatewords_html:60}}
                            </div>
                        </a>
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="mr-2">
                                    <img class="rounded-circle" width="45" height="45"
                                        src="{% if answer.user.display_img %}{{answer.user.display_img.url}} {% else %} {% static 'imgs/no_display_img.jpg' %} {% endif %}">
                                </div>
                                <div class="ml-2">
                                    <div class="p m-0">
                                        {% if answer.is_anonymous %}
                                        <i>Anonymous</i>
                                        {% else %}
                                        <a href="{% url 'users:profile' answer.user.slug %}"
                                            class="text-decoration-none">
                                            <b>
                                                {{answer.user.first_name | title}}
                                                {{answer.user.last_name | title}}
                                            </b>
                                        </a> |
                                        {{answer.created_date|date:'d F, Y'}}
                                        {% if answer.created_date != answer.updated_date %}
                                        (Edited)
                                        {% endif %}
                                        {% endif %}
                                    </div>
                                    <div class="h7 text-muted">{{answer.user.bio}}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% else %}
            <h4 class="crim text-center mb-4">{{user.first_name | title}} {{user.last_name | title}} has not pinned any
                answers.
            </h4>
            {% endif %}

            {% endblock profile %}
        </div>
        <div class="col-md-3">
            <div class="d-flex justify-content-between">
                <h6 class="text-muted">Credentials & Highlights</h6>
            </div>
            <hr class="my-2">
            <div class="workplace mb-2">
                {% if user.workplace_set.all %}
                <span><img src="{% static 'imgs/qnA/briefcase.svg' %}" alt="Works at"></span>
                <span>{{user.workplace_set.all.0.position}} at {{user.workplace_set.all.0.company_name}}</span>
                {% if user.workplace_set.all.0.start_year %}
                <span class="text-muted">
                    {% if user.workplace_set.all.0.is_currently_working or not user.workplace_set.all.0.end_year %}
                    ({{user.workplace_set.all.0.start_year}} - Present)
                    {% else %}
                    ({{user.workplace_set.all.0.start_year}} - {{user.workplace_set.all.0.end_year}})
                    {% endif %}
                </span>
                {% endif %}
                {% if user == request.user %}
                <span>
                    <a href="{% url 'users:workplace_edit' %}" class="badge badge-info align-self-center">Edit</a>
                    <a href="{% url 'users:workplace_delete' %}" class="badge badge-danger align-self-center">Remove</a>
                </span>
                {% endif %}
                {% elif user == request.user %}
                <span><img src="{% static 'imgs/qnA/briefcase.svg' %}" alt="Works at"></span>
                <span>
                    <a href="{% url 'users:workplace_add' %}" class="badge badge-primary align-self-center">Add
                        Workplace</a>
                </span>
                {% endif %}
            </div>
            <div class="education mb-2">
                {% if user.education_set.all %}
                <span><img src="{% static 'imgs/qnA/building.svg' %}" alt="Works at"></span>
                <span>Studied At {{user.education_set.all.0.school_name}}</span>
                {% if user.education_set.all.0.start_year %}
                <span class="text-muted">
                    {% if user.education_set.all.0.is_currently_studying or not user.education_set.all.0.end_year %}
                    ({{user.education_set.all.0.start_year}} - Present)
                    {% else %}
                    ({{user.education_set.all.0.start_year}} - {{user.education_set.all.0.end_year}})
                    {% endif %}
                </span>
                {% endif %}
                {% if user == request.user %}
                <span>
                    <a href="{% url 'users:education_edit' %}" class="badge badge-info align-self-center">Edit</a>
                    <a href="{% url 'users:education_delete' %}" class="badge badge-danger align-self-center">Remove</a>
                </span>
                {% endif %}
                {% elif user == request.user %}
                <span><img src="{% static 'imgs/qnA/building.svg' %}" alt="Works at"></span>
                <span>
                    <a href="{% url 'users:education_add' %}" class="badge badge-primary align-self-center">Add
                        Education</a>
                </span>
                {% endif %}
            </div>
            <div class="location">
                {% if user.location %}
                <span><img src="{% static 'imgs/qnA/map.svg' %}" alt="Lives at"></span>
                <span>Lives in {{user.location}}</span>
                {% if user == request.user %}
                <span>
                    <a href="{% url 'users:edit' %}" class="badge badge-info align-self-center">Edit</a>
                    <a href="{% url 'users:edit' %}" class="badge badge-danger align-self-center">Remove</a>
                </span>
                {% endif %}
                {% elif user == request.user %}
                <span><img src="{% static 'imgs/qnA/map.svg' %}" alt="lives at"></span>
                <span>
                    <a href="{% url 'users:edit' %}" class="badge badge-primary align-self-center">Add
                        Location</a>
                </span>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
<script src="{% static 'js/vote.js' %}"></script>
<script src="{% static 'js/follow_toggler.js' %}"></script>
{% endblock scripts %}

templates/users/user_followers.html
{% extends "users/user_detail.html" %}
{% load is_following %}
{% load static %}
{% block profile %}
<div class="user-profile">
    <h6 class="text-muted">{{followers|length}} Followers</h6>
    {% if followers %}
    {% for follower in followers %}
    <div class="card mb-2">
        <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="mr-2">
                        <img class="rounded-circle" width="45" height="45"
                            src="{% if follower.from_user.display_img %}{{follower.from_user.display_img.url}} {% else %} {% static 'imgs/no_display_img.jpg' %} {% endif %}">
                    </div>
                    <div class="ml-2">
                        <div class="p m-0">
                            <b>
                                <a href="{% url 'users:profile' follower.from_user.slug %}">
                                    {{follower.from_user.first_name}}
                                    {{follower.from_user.last_name}}
                                </a>
                            </b>
                        </div>
                        <div class="h7 text-muted">{{follower.from_user.bio}}</div>
                    </div>
                </div>
                <div>
                    {% is_following request.user.pk follower.from_user.pk as is_following %}
                    {% if follower.from_user.pk != request.user.pk %}
                    {% if is_following %}
                    <input type="button" value="Unfollow" name="follow_list"
                        class="btn btn-outline-danger follow follow{{follower.from_user.slug}}"
                        data-to-user="{{follower.from_user.slug}}" />
                    {% else %}
                    <input type="button" value="Follow" name="follow_list"
                        class="btn btn-danger follow follow{{follower.from_user.slug}}"
                        data-to-user="{{follower.from_user.slug}}" />
                    {% endif %}

                    {% else %}
                    <a class="btn btn-outline-danger" href="{% url 'users:profile' follower.from_user.slug %}"
                        role="button" id="follow">View Your Profile</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h4>{{user.first_name}} {{user.last_name}} has no followers yet.</h4>
    {% endif %}
</div>
{% endblock profile %}